version: '3.8'
services:
  db:
    image: postgres:17
    container_name: blog_postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
  web:
    build: .
    container_name: blog_web
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - ./:/app
      - dist:/app/dist
    tty: true
    depends_on:
      db:
        condition: service_healthy
volumes:
  postgres_data:
  dist:
